# -*- coding: utf-8 -*-
"""Perceptron .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sw7TND8L9ptDne2h_0Hgn3VVBx5qZFgT
"""

import numpy as np
import pandas as pd

#if bais check box get random value and pass it to the function

# #features must be =(2,1) and  #classes =2
def perceptron(features , classes , eta , num_of_epochs,bais=0 ):
  W=np.random.rand(1,2)

  for epoch in range(num_of_epochs):

    for X_i , T_i in zip(features, classes):

      y_i=np.dot(W, X_i)+bais
      # activation function
      if y_i<0 :
        y_i=-1
      else :
         y_i=1


      #calculate Error
      if y_i != T_i:
        L=(T_i-y_i)

        #updating Wieght

        W=W+eta*(T_i-y_i)*X_i



    return W