# -*- coding: utf-8 -*-
"""Perceptron .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sw7TND8L9ptDne2h_0Hgn3VVBx5qZFgT
"""

import numpy as np


# if bais check box get random value and pass it to the function


def perceptron(X, y, learning_rate=0.01, epochs=1000, b=0):
    samples, feat = X.shape
    W = np.random.rand(feat)

    for _ in range(epochs):
        for i, x in enumerate(X):
            y_pred = np.dot(x, W) + b

            if y_pred >= 0:
                y_pred = 1
            else:
                y_pred = -1
            upt = learning_rate * (y[i] - y_pred)
            W += upt * x

    return W
