# -*- coding: utf-8 -*-
"""feedForward.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TMMOnBtW0jPKXa9DZNeplFpfQAWmm2J5
"""

hidden_layers=3
neurons=[10,10,10]

"""# **Forward**"""

import numpy as np

#This function should be called in a loop each training set >> call this function

def feedForward(Input_layer,neurons,wieght_matrices):

  neurons.append(3)
  #contains all f for each layer
  array_of_fs=[]

  for i in range(hidden_layers+1):
    #print("Layer: ",i)

    #f contains net value for wach neuron
    f=[]

    for n in range(neurons[i]):
      #print("Neuron: ",n)
      #print(wieght_matrices[i][n])

      if i==0:
        f_i=np.dot(wieght_matrices[i][n],Input_layer)
        f.append(f_i)
      else:
        f_i=np.dot(wieght_matrices[i][n],array_of_fs[i-1])
        f.append(f_i)


    array_of_fs.append(f)
  return  array_of_fs

Input_layer=[1,1,1,1,1,1]
array_of_fs=feedForward(Input_layer,neurons,wieght_matrices)
print(array_of_fs)